return {
  'catppuccin/nvim',
  lazy = false,
  name = 'catppuccin',
  priority = 1000,
  opts = {
    color_overrides = {
      all = {
        white = "#D9E0EE",
        darker_black = "#191828",
        black = "#1E1D2D", --  nvim bg
        black2 = "#252434",
        one_bg = "#2d2c3c", -- real bg of onedark
        one_bg2 = "#363545",
        one_bg3 = "#3e3d4d",
        grey = "#474656",
        grey_fg = "#4e4d5d",
        grey_fg2 = "#555464",
        light_grey = "#605f6f",
        red = "#F38BA8",
        baby_pink = "#ffa5c3",
        pink = "#F5C2E7",
        line = "#383747", -- for lines like vertsplit
        green = "#ABE9B3",
        vibrant_green = "#b6f4be",
        nord_blue = "#8bc2f0",
        blue = "#89B4FA",
        yellow = "#FAE3B0",
        sun = "#ffe9b6",
        purple = "#d0a9e5",
        dark_purple = "#c7a0dc",
        teal = "#B5E8E0",
        orange = "#F8BD96",
        cyan = "#89DCEB",
        statusline_bg = "#232232",
        lightbg = "#2f2e3e",
        pmenu_bg = "#ABE9B3",
        folder_bg = "#89B4FA",
        lavender = "#c7d1ff",
      }
    },
    custom_highlights = function(colors)
      return {
        -- Cmp integrations
        CmpItemAbbr = { fg = colors.overlay2 },
        CmpItemAbbrDeprecated = { fg = colors.overlay0, style = { 'strikethrough' } },
        CmpItemKind = { fg = colors.blue },
        CmpItemMenu = { fg = colors.text },
        CmpItemAbbrMatch = { fg = colors.text, style = { 'bold' } },
        CmpItemAbbrMatchFuzzy = { fg =  colors.text, style = { 'bold' } },

        CmpDoc = { bg = colors.darker_black },
        CmpDocBorder = { fg = colors.darker_black, bg = colors.darker_black },
        CmpPmenu = {
          bg = colors.black
        },
        CmpBorder = { fg = colors.blue },
        CmpSel = { fg = colors.base, bg = colors.green },

        -- Cmp item kind integrations
        CmpItemKindConstant = { fg = colors.peach },
        CmpItemKindFunction = { fg = colors.blue },
        CmpItemKindIdentifier = { fg = colors.flamingo },
        CmpItemKindField = { fg = colors.green },
        CmpItemKindVariable = { fg = colors.flamingo },
        CmpItemKindSnippet = { fg = colors.red },
        CmpItemKindText = { fg = colors.teal },
        CmpItemKindStructure = { fg = colors.yellow },
        CmpItemKindType = { fg = colors.green },
        CmpItemKindKeyword = { fg = colors.red },
        CmpItemKindMethod = { fg = colors.blue },
        CmpItemKindConstructor = { fg = colors.blue },
        CmpItemKindFolder = { fg = colors.blue },
        CmpItemKindModule = { fg = colors.yellow },
        CmpItemKindProperty = { fg = colors.green },
        CmpItemKindEnum = { fg = colors.blue },
        CmpItemKindUnit = { fg = colors.green },
        CmpItemKindClass = { fg = colors.teal },
        CmpItemKindFile = { fg = colors.blue },
        CmpItemKindInterface = { fg = colors.green },
        CmpItemKindColor = { fg = colors.white },
        CmpItemKindReference = { fg = colors.red },
        CmpItemKindEnumMember = { fg = colors.purple },
        CmpItemKindStruct = { fg = colors.blue },
        CmpItemKindValue = { fg = colors.cyan },
        CmpItemKindEvent = { fg = colors.yellow },
        CmpItemKindOperator = { fg = colors.blue },
        CmpItemKindTypeParameter = { fg = colors.blue },
        CmpItemKindCopilot = { fg = colors.green },
        CmpItemKindCodeium = { fg = colors.vibrant_green },
        CmpItemKindTabNine = { fg = colors.baby_pink },

        -- Devicons
        DevIconDefault = { fg = colors.red },
        DevIconc = { fg = colors.blue },
        DevIconcss = { fg = colors.blue },
        DevIcondeb = { fg = colors.cyan },
        DevIconDockerfile = { fg = colors.cyan },
        DevIconhtml = { fg = colors.baby_pink },
        DevIconjpeg = { fg = colors.dark_purple },
        DevIconjpg = { fg = colors.dark_purple },
        DevIconjs = { fg = colors.sun },
        DevIconkt = { fg = colors.orange },
        DevIconlock = { fg = colors.red },
        DevIconlua = { fg = colors.blue },
        DevIconmp3 = { fg = colors.white },
        DevIconmp4 = { fg = colors.white },
        DevIconout = { fg = colors.white },
        DevIconpng = { fg = colors.dark_purple },
        DevIconpy = { fg = colors.cyan },
        DevIcontoml = { fg = colors.blue },
        DevIconts = { fg = colors.teal },
        DevIconttf = { fg = colors.white },
        DevIconrb = { fg = colors.pink },
        DevIconrpm = { fg = colors.orange },
        DevIconvue = { fg = colors.vibrant_green },
        DevIconwoff = { fg = colors.white },
        DevIconwoff2 = { fg = colors.white },
        DevIconxz = { fg = colors.sun },
        DevIconzip = { fg = colors.sun },
        DevIconZig = { fg = colors.orange },
        DevIconMd = { fg = colors.blue },
        DevIconTSX = { fg = colors.blue },
        DevIconJSX = { fg = colors.blue },
        DevIconSvelte = { fg = colors.red },
        DevIconJava = { fg = colors.orange },
        DevIconDart = { fg = colors.cyan },

        -- Nvim-tree integrations
        NvimTreeEmptyFolderName = { fg = colors.folder_bg },
        NvimTreeEndOfBuffer = { fg = colors.darker_black },
        NvimTreeFolderIcon = { fg = colors.folder_bg },
        NvimTreeFolderName = { fg = colors.folder_bg },
        NvimTreeFolderArrowOpen = { fg = colors.folder_bg },
        NvimTreeFolderArrowClosed = { fg = colors.grey_fg },
        NvimTreeGitDirty = { fg = colors.red },
        NvimTreeIndentMaker = { fg = colors.grey_fg },
        NvimTreeNormal = { bg = colors.darker_black },
        NvimTreeNormalNC = { bg = colors.darker_black },
        NvimTreeOpenedFolderName = { fg = colors.folder_bg },
        NvimTreeGitIgnored = { fg = colors.light_grey },
        NvimTreeWinSeparator = {
          fg = colors.darker_black,
          bg = colors.darker_black,
        },
        NvimTreeWindowPicker = {
          fg = colors.red,
          bg = colors.black2,
        },
        NvimTreeCursorLine = {
          bg = colors.black2,
        },
        NvimTreeGitNew = {
          fg = colors.yellow,
        },
        NvimGitDeleted = {
          fg = colors.red,
        },
        NvimTreeSpecialFile = {
          fg = colors.yellow,
          bold = true,
        },
        NvimTreeRootFolder = {
          fg = colors.red,
          bold = true,
        },

        -- Which key integrations
        WhichKey = { link = 'Normal'},
        WhichKeyBorder = { link = 'FloatBorder' },
        WhichKeyGroup = { fg = colors.blue },
        WhichKeySeparator = { fg = colors.overlay0 },
        WhichKeyDesc = { fg = colors.pink },
        WhichKeyValue = { fg = colors.overlay0 },
      }
    end,
    integrations = {
      barbar = true,
      cmp = true,
      dap = true,
      dap_ui = true,
      gitsigns = true,
      harpoon = true,
      mason = true,
      native_lsp = {
        enabled = true,
        virtual_text = {
          errors = { 'italic' },
          hints = { 'italic' },
          warnings = { 'italic' },
          information = { 'italic' },
        },
        underlines = {
          errors = { 'underline' },
          hints = { 'underline' },
          warnings = { 'underline' },
          information = { 'underline' },
        },
        inlay_hints = {
          background = true,
        },
      },
      nvimtree = true,
      semantic_tokens = true,
      telescope = {
        enabled = true,
      },
      treesitter = true,
      which_key = true,
    },
  },
  config = function(_, opts)
    require('catppuccin').setup(opts)
    vim.cmd('colorscheme catppuccin')
  end
}
