local opts = {
	flavour = "mocha",
	background = {
		light = "latte",
		dark = "mocha",
	},
	transparent_background = false,
	show_end_of_buffer = false,
	term_colors = false,
	dim_inactive = {
		enabled = false, -- dims the background color of inactive window
		shade = "dark",
		percentage = 0.15, -- percentage of the shade to apply to the inactive window
	},
	no_italic = false,
	no_bold = false,
	no_underline = false,
	styles = {
		comments = { "italic" },
		conditionals = { "italic" },
		loops = {},
		functions = {},
		keywords = {},
		strings = {},
		variables = {},
		numbers = {},
		booleans = {},
		properties = {},
		types = {},
		operators = {},
	},
	color_overrides = {
		all = {
			baby_pink = "#ffa5c3",
			base = "#1e1e2e",
			black = "#1E1D2D", --  nvim bg
			black2 = "#252434",
			blue = "#89b4fa",
			crust = "#11111b",
			cyan = "#89DCEB",
			darker_black = "#191828",
			dark_purple = "#c7a0dc",
			flamingo = "#f2cdcd",
			folder_bg = "#89B4FA",
			green = "#a6e3a1",
			grey = "#474656",
			grey_fg = "#4e4d5d",
			grey_fg2 = "#555464",
			lavender = "#b4befe",
			lightbg = "#2f2e3e",
			light_grey = "#605f6f",
			line = "#383747", -- for lines like vertsplit
			mantle = "#181825",
			maroon = "#eba0ac",
			mauve = "#cba6f7",
			nord_blue = "#8bc2f0",
			one_bg = "#2d2c3c", -- real bg of onedark
			one_bg2 = "#363545",
			one_bg3 = "#3e3d4d",
			orange = "#F8BD96",
			overlay2 = "#9399b2",
			overlay1 = "#7f849c",
			overlay0 = "#6c7086",
			pmenu_bg = "#ABE9B3",
			peach = "#fab387",
			pink = "#f5c2e7",
			purple = "#d0a9e5",
			red = "#f38ba8",
			rosewater = "#f5e0dc",
			sapphire = "#74c7ec",
			statusline_bg = "#232232",
			sky = "#89dceb",
			subtext1 = "#bac2de",
			subtext0 = "#a6adc8",
			sun = "#ffe9b6",
			surface2 = "#585b70",
			surface1 = "#45475a",
			surface0 = "#313244",
			teal = "#94e2d5",
			text = "#cdd6f4",
			vibrant_green = "#b6f4be",
			white = "#D9E0EE",
			yellow = "#f9e2af",
		},
	},
	custom_highlights = function(colors)
		return {
			-- Barbar integrations
			BufferCurrent = { bg = colors.base, fg = colors.text },
			BufferCurrentBtn = { bg = colors.base, fg = colors.red },
			BufferCurrentIndex = { bg = colors.base, fg = colors.blue },
			BufferCurrentMod = { bg = colors.base, fg = colors.yellow },
			BufferCurrentModBtn = { bg = colors.base, fg = colors.yellow },
			BufferCurrentSign = { bg = colors.base, fg = colors.blue },
			BufferCurrentTarget = { bg = colors.base, fg = colors.red },
			BufferCurrentHINT = { bg = colors.base, fg = colors.green },
			BufferCurrentWARN = { bg = colors.base, fg = colors.yellow },
			BufferCurrentERROR = { bg = colors.base, fg = colors.red },
			BufferCurrentINFO = { bg = colors.base, fg = colors.teal },
			BufferVisible = { bg = colors.base, fg = colors.text },
			BufferVisibleBtn = { bg = colors.base, fg = colors.red },
			BufferVisibleIndex = { bg = colors.base, fg = colors.blue },
			BufferVisibleMod = { bg = colors.base, fg = colors.yellow },
			BufferVisibleModBtn = { bg = colors.base, fg = colors.yellow },
			BufferVisibleSign = { bg = colors.base, fg = colors.blue },
			BufferVisibleTarget = { bg = colors.base, fg = colors.red },
			BufferInactive = { bg = colors.mantle, fg = colors.overlay0 },
			BufferInactiveBtn = { bg = colors.mantle, fg = colors.overlay0 },
			BufferInactiveIndex = { bg = colors.mantle, fg = colors.overlay0 },
			BufferInactiveMod = { bg = colors.mantle, fg = colors.yellow },
			BufferInactiveModBtn = { bg = colors.mantle, fg = colors.yellow },
			BufferInactiveSign = { bg = colors.mantle, fg = colors.blue },
			BufferInactiveTarget = { bg = colors.mantle, fg = colors.red },
			BufferTabpages = { bg = colors.mantle, fg = colors.none },
			BufferTabpage = { bg = colors.mantle, fg = colors.blue },

			-- Cmp integrations
			CmpItemAbbr = { fg = colors.overlay2 },
			CmpItemAbbrDeprecated = { fg = colors.overlay0, style = { "strikethrough" } },
			CmpItemKind = { fg = colors.blue },
			CmpItemMenu = { fg = colors.text },
			CmpItemAbbrMatch = { fg = colors.text, style = { "bold" } },
			CmpItemAbbrMatchFuzzy = { fg = colors.text, style = { "bold" } },

			CmpDoc = { bg = colors.darker_black },
			CmpDocBorder = { fg = colors.darker_black, bg = colors.darker_black },
			CmpPmenu = {
				bg = colors.black,
			},
			CmpBorder = { fg = colors.blue },
			CmpSel = { fg = colors.base, bg = colors.green },

			-- Cmp item kind integrations
			CmpItemKindConstant = { fg = colors.peach },
			CmpItemKindFunction = { fg = colors.blue },
			CmpItemKindIdentifier = { fg = colors.flamingo },
			CmpItemKindField = { fg = colors.green },
			CmpItemKindVariable = { fg = colors.flamingo },
			CmpItemKindSnippet = { fg = colors.red },
			CmpItemKindText = { fg = colors.teal },
			CmpItemKindStructure = { fg = colors.yellow },
			CmpItemKindType = { fg = colors.green },
			CmpItemKindKeyword = { fg = colors.red },
			CmpItemKindMethod = { fg = colors.blue },
			CmpItemKindConstructor = { fg = colors.blue },
			CmpItemKindFolder = { fg = colors.blue },
			CmpItemKindModule = { fg = colors.yellow },
			CmpItemKindProperty = { fg = colors.green },
			CmpItemKindEnum = { fg = colors.blue },
			CmpItemKindUnit = { fg = colors.green },
			CmpItemKindClass = { fg = colors.teal },
			CmpItemKindFile = { fg = colors.blue },
			CmpItemKindInterface = { fg = colors.green },
			CmpItemKindColor = { fg = colors.white },
			CmpItemKindReference = { fg = colors.red },
			CmpItemKindEnumMember = { fg = colors.purple },
			CmpItemKindStruct = { fg = colors.blue },
			CmpItemKindValue = { fg = colors.cyan },
			CmpItemKindEvent = { fg = colors.yellow },
			CmpItemKindOperator = { fg = colors.blue },
			CmpItemKindTypeParameter = { fg = colors.blue },
			CmpItemKindCopilot = { fg = colors.green },
			CmpItemKindCodeium = { fg = colors.vibrant_green },
			CmpItemKindTabNine = { fg = colors.baby_pink },

			-- Devicons
			DevIconDefault = { fg = colors.red },
			DevIconc = { fg = colors.blue },
			DevIconcss = { fg = colors.blue },
			DevIcondeb = { fg = colors.cyan },
			DevIconDockerfile = { fg = colors.cyan },
			DevIconhtml = { fg = colors.baby_pink },
			DevIconjpeg = { fg = colors.dark_purple },
			DevIconjpg = { fg = colors.dark_purple },
			DevIconjs = { fg = colors.sun },
			DevIconkt = { fg = colors.orange },
			DevIconlock = { fg = colors.red },
			DevIconlua = { fg = colors.blue },
			DevIconmp3 = { fg = colors.white },
			DevIconmp4 = { fg = colors.white },
			DevIconout = { fg = colors.white },
			DevIconpng = { fg = colors.dark_purple },
			DevIconpy = { fg = colors.cyan },
			DevIcontoml = { fg = colors.blue },
			DevIconts = { fg = colors.teal },
			DevIconttf = { fg = colors.white },
			DevIconrb = { fg = colors.pink },
			DevIconrpm = { fg = colors.orange },
			DevIconvue = { fg = colors.vibrant_green },
			DevIconwoff = { fg = colors.white },
			DevIconwoff2 = { fg = colors.white },
			DevIconxz = { fg = colors.sun },
			DevIconzip = { fg = colors.sun },
			DevIconZig = { fg = colors.orange },
			DevIconMd = { fg = colors.blue },
			DevIconTSX = { fg = colors.blue },
			DevIconJSX = { fg = colors.blue },
			DevIconSvelte = { fg = colors.red },
			DevIconJava = { fg = colors.orange },
			DevIconDart = { fg = colors.cyan },

			-- GitSigns integrations
			GitSignsAdd = { bg = colors.base, fg = colors.green },
			GitSignsChange = { bg = colors.base, fg = colors.yellow },
			GitSignsDelete = { bg = colors.base, fg = colors.red },
			GitSignsChangedelete = { bg = colors.base, fg = colors.purple },
			GitSignsTopdelete = { bg = colors.base, fg = colors.red },
			GitSignsUntracked = { bg = colors.base, fg = colors.orange },

			-- Lualine integrations
			LuaLineEmptySep = { bg = colors.surface1 },
			LuaLineNormalSectionA = { bg = colors.blue, fg = colors.mantle, bold = true },
			LuaLineNormalSectionB = { bg = colors.surface0, fg = colors.blue },
			LuaLineNormalSectionC = { bg = colors.mantle, fg = colors.overlay0 },
			LuaLineInsertSectionA = { bg = colors.green, fg = colors.mantle, bold = true },
			LuaLineInsertSectionB = { bg = colors.surface0, fg = colors.green },
			LuaLineVisualSectionA = { bg = colors.lavender, fg = colors.mantle, bold = true },
			LuaLineVisualSectionB = { bg = colors.surface0, fg = colors.lavender },
			LuaLineFileName = { bg = colors.surface0, fg = colors.blue },
			LuaLineGitBranch = { bg = colors.mantle, fg = colors.overlay0 },
			LuaLineLspStatus = { bg = colors.mantle, fg = colors.blue },
			LuaLineFolderIcon = { bg = colors.pink, fg = colors.mantle, bold = true },
			LuaLineStackIcon = { bg = colors.green, fg = colors.mantle },
			LuaLineCwd = { fg = colors.text, bg = colors.surface0 },
			LuaLineProgress = { fg = colors.green, bg = colors.mantle },
			LuaLineDiffAdd = { fg = colors.green, bg = colors.mantle },
			LuaLineDiffChange = { fg = colors.yellow, bg = colors.mantle },
			LuaLineDiffDelete = { fg = colors.red, bg = colors.mantle },
			DiagnosticError = { fg = colors.red, bg = colors.mantle },
			DiagnosticWarn = { fg = colors.yellow, bg = colors.mantle },
			DiagnosticInfo = { fg = colors.blue, bg = colors.mantle },
			DiagnosticHint = { fg = colors.teal, bg = colors.mantle },

			-- Nvim-tree integrations
			NvimTreeCursorLine = {
				bg = colors.black2,
			},
			NvimTreeEmptyFolderName = { fg = colors.folder_bg },
			NvimTreeEndOfBuffer = { fg = colors.darker_black },
			NvimTreeFolderIcon = { fg = colors.blue },
			NvimTreeFolderName = { fg = colors.blue },
			NvimTreeFolderArrowOpen = { fg = colors.folder_bg },
			NvimTreeFolderArrowClosed = { fg = colors.grey_fg },
			NvimTreeIndentMarker = { fg = colors.surface0 },
			NvimTreeNormal = { fg = colors.text, bg = colors.mantle },
			NvimTreeNormalNC = { bg = colors.mantle },
			NvimTreeOpenedFolderName = { fg = colors.folder_bg },
			NvimTreeRootFolder = {
				fg = colors.red,
				bold = true,
			},
			NvimTreeSpecialFile = {
				fg = colors.flamingo,
				bold = true,
			},
			NvimTreeStatusLineNc = { bg = colors.mantle, fg = colors.mantle },
			NvimTreeWindowPicker = {
				fg = colors.red,
				bg = colors.black2,
			},
			NvimTreeWinSeparator = {
				fg = colors.base,
				bg = colors.base,
			},

			-- Nvim-tree Git highlight groups
			NvimTreeGitNew = {
				fg = colors.green,
			},
			NvimTreeGitNewIcon = {
				fg = colors.green,
			},
			NvimGitDeleted = {
				fg = colors.red,
			},
			NvimTreeGitDeletedIcon = {
				fg = colors.red,
			},
			NvimTreeGitDirty = { fg = colors.orange },
			NvimTreeGitDirtyIcon = { fg = colors.orange },
			NvimTreeGitIgnored = { fg = colors.black2 },
			NvimTreeGitIgnoredIcon = { fg = colors.black2 },
			NvimTreeGitMergedFile = { fg = colors.orange },
			NvimTreeGitMergedIcon = { fg = colors.orange },
			NvimTreeGitRenamed = { fg = colors.blue },
			NvimTreeGitRenamedIcon = { fg = colors.blue },
			NvimTreeGitStaged = { fg = colors.green },
			NvimTreeGitStagedIcon = { fg = colors.green },
			NvimTreeGitUnmerged = { fg = colors.orange },
			NvimTreeGitUnmergedIcon = { fg = colors.orange },

			-- Telescope integrations
			TelescopeBorder = { fg = colors.blue, bg = colors.darker_black },
			TelescopeMatching = { fg = colors.blue },
			TelescopeNormal = { bg = colors.darker_black },
			TelescopePromptBorder = { fg = colors.blue, bg = colors.darker_black },
			TelescopePromptNormal = { fg = colors.text, bg = colors.darker_black },
			TelescopePromptPrefix = { fg = colors.flamingo, bg = colors.darker_black },
			TelescopePreviewTitle = { fg = colors.base, bg = colors.green },
			TelescopeResultsTitle = { fg = colors.darker_black, bg = colors.lavender },
			TelescopeSelection = { fg = colors.text, bg = colors.black2, style = { "bold" } },
			TelescopeSelectionCaret = { fg = colors.flamingo },

			-- Which key integrations
			WhichKey = { link = "NormalFloat" },
			WhichKeyBorder = { link = "FloatBorder" },
			WhichKeyGroup = { fg = colors.blue },
			WhichKeySeparator = { fg = colors.overlay0 },
			WhichKeyDesc = { fg = colors.pink },
			WhichKeyValue = { fg = colors.overlay0 },
		}
	end,
	integrations = {
		barbar = true,
		cmp = true,
		dap = function()
			local sign = vim.fn.sign_define

			sign("DapBreakpoint", { text = "●", texthl = "DapBreakpoint", linehl = "", numhl = "" })
			sign("DapBreakpointCondition", { text = "●", texthl = "DapBreakpointCondition", linehl = "", numhl = "" })
			sign("DapLogPoint", { text = "◆", texthl = "DapLogPoint", linehl = "", numhl = "" })
		end,
		dap_ui = true,
		gitsigns = true,
		harpoon = true,
		indent_blankline = {
			enabled = true,
			scope_color = "",
			colored_indent_levels = false,
		},
		markdown = true,
		mason = true,
		native_lsp = {
			enabled = true,
			virtual_text = {
				errors = { "italic" },
				hints = { "italic" },
				warnings = { "italic" },
				information = { "italic" },
			},
			underlines = {
				errors = { "underline" },
				hints = { "underline" },
				warnings = { "underline" },
				information = { "underline" },
			},
			inlay_hints = {
				background = true,
			},
		},
		nvimtree = true,
		semantic_tokens = true,
		telescope = {
			enabled = true,
			style = "nvchad",
		},
		treesitter = true,
		which_key = true,
	},
}

return opts
